# Generated by Django 4.2.3 on 2023-08-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-date_create'], 'permissions': {('terbitkan', 'Terbitkan Artikel')}},
        ),
    ]
