# Generated by Django 4.2.3 on 2023-08-09 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_artikel_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='penulis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
