# Generated by Django 4.2.3 on 2023-08-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_artikel_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
